### ISSUE TITLE
USB storage devices not working with kernels 3.0.y to 3.10.y

### ISSUE THREAD

**Issue by DeltaResero** [DeltaResero/GC-Wii-Linux-Kernels#4]
I'm still in the process of backporting stuff and hopefully will have this fixed soon.  For now, either use more recent kernels or use one prior to the 3.0.y version.  The 3.12.y and newer versions should have the fix included now to allow for USB storage devices to be used.

**Comment by neagix** [comment]
I do not verify this issue; actually SDHC gets broken at some point (needs bisection) on the v3.x tree, but USB storage is fine.

**Comment by DeltaResero** [comment]
Thanks, I forgot to close this. I fixed the patch itself when I pulled all the kernels from their separate repositories into this one.
