### ISSUE TITLE
Relases MIKEp7 patch

### ISSUE THREAD

**Issue by DeepHorizons** [DeltaResero/GC-Wii-Linux-Kernels#8]
Would it be possible to release the patch, I would like to work on some fixes and the patch would be helpful.

**Comment by DeltaResero** [comment]
The MIKEp7 patch is in the commits for each of the branches. For example,the patch that applies to the 3.12 kernel can be found here (add ".patch" to the end of the URL to get the patch): https://github.com/DeltaResero/GC-Wii-Linux-Kernels/commit/4162eee587e1eabff1a083c9ee8b5deb3e569b88
